### PR TITLE
Add missing components

### PR DESCRIPTION
**Pull request by evanplaice**
Without the `components` folder, it's not possible to load syntax highlighting for languages that aren't included in the prismjs core (ex python).

This PR adds the `components` folder as well as sets up scripts to automate the process of copying over both the `themes` and `components` folders.

Ref #1

### CODE REVIEW

**Comment by honzabilek4** [comment]
Thanks a lot! 🎉

**Comment by evanplaice** [comment]
Oh, lol. That was quick. Thanks!

**Comment by evanplaice** [comment]
Can you publish a new version to NPM? The current (ie 1.1.2) doesn't include this fix.

**Comment by honzabilek4** [comment]
I'm on it 🙂

**Comment by honzabilek4** [comment]
Here you go. The package is now on v1.2.0.

**Pull request merged**
